# Generated by Django 5.1.2 on 2024-10-26 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('date', models.DateField(blank=True, null=True)),
                ('location', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=200)),
                ('add_category', models.ManyToManyField(to='categories.category')),
            ],
        ),
    ]
