# Generated by Django 5.1.2 on 2024-10-26 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='add_category',
            new_name='category',
        ),
    ]
